/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taximetro;

import static es.javiergarbedo.coordinateslib.CoordinatesConverter.decimalToDMS;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.JOptionPane;
import org.apache.commons.lang3.time.DurationFormatUtils;
import org.apache.commons.lang3.time.StopWatch;
import org.apache.commons.validator.routines.CreditCardValidator;

/**
 *
 * @author JoseManuel
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1longitud = new javax.swing.JTextField();
        jTextField1latitud1 = new javax.swing.JTextField();
        jLabel3Latitud = new javax.swing.JLabel();
        jLabel4Longitud = new javax.swing.JLabel();
        jLabel5imagenTaxi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1destino = new javax.swing.JTextField();
        jButton1banderaVerde = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1ticket = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jTextField1tarjetaCredito = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton1cancelar = new javax.swing.JButton();
        jLabel7mapa = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(" Posición GPS Inicio"));

        jLabel1.setText("Latitud: ");

        jLabel2.setText("Longitud: ");

        jTextField1latitud1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1latitud1ActionPerformed(evt);
            }
        });

        jLabel3Latitud.setText("jLabel3");

        jLabel4Longitud.setText("jLabel3");

        jLabel5imagenTaxi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/taxi copia.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4Longitud))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1latitud1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3Latitud)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5imagenTaxi)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1latitud1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3Latitud))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1longitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4Longitud)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5imagenTaxi, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del proyecto"));

        jLabel5.setText("Destino: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1destino)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1banderaVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banderaVerde copia.png"))); // NOI18N
        jButton1banderaVerde.setText("jButton1");
        jButton1banderaVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1banderaVerdeActionPerformed(evt);
            }
        });

        jTextArea1ticket.setColumns(20);
        jTextArea1ticket.setRows(5);
        jScrollPane1.setViewportView(jTextArea1ticket);

        jLabel6.setText("Tarjeta de Crédito: ");

        jButton1.setText("Comprobar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton1cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar copia copia2.png"))); // NOI18N
        jButton1cancelar.setText("jButton1");
        jButton1cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1cancelarActionPerformed(evt);
            }
        });

        jLabel7mapa.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Mapa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jButton1banderaVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel7mapa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel7)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField1tarjetaCredito)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1banderaVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7mapa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1tarjetaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1latitud1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1latitud1ActionPerformed
        //COORDENADAS LONGITUD
        
        
        
        
    }//GEN-LAST:event_jTextField1latitud1ActionPerformed

        
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Variables
        String numTarjeta, mensaje;
        boolean validacionTarjeta;
        //Tarjeta
        CreditCardValidator validarTarjeta = new CreditCardValidator();
        validacionTarjeta = validarTarjeta.isValid(jTextField1tarjetaCredito.getText());
        mensaje = (validacionTarjeta == true) ? "La tarjeta es válida" : "La tarjeta no es válida" ;
        JOptionPane.showMessageDialog(this, mensaje, "Validacion de tarjeta", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

        //Variable duración tiempo
        StopWatch duracion = new StopWatch();
        
        String duracionFormato;
        
    private void jButton1banderaVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1banderaVerdeActionPerformed

        //ACTIVAR-DESACTIVAR BOTONES
        jButton1cancelar.setEnabled(true);
        jButton1banderaVerde.setEnabled(false);
        
        //VARIABLE Latitud-Longitud
        double latitud, longitud;
        
        //MAPA
        
        //  Cambia los siguientes valores por las direciones de origen y destino deseadas
        
        String origen = jTextField1latitud1.getText() + "," + jTextField1longitud.getText();
        String destino = jTextField1destino.getText();
        
        /*  Hay que sustituir los espacios por el carácter %20 para que se
        interprete bien la URL que se generará  */
        
        destino = destino.replaceAll(" ", "%20");
        
        /*  Cambia el nombre [etiqueta] por el nombre de un objeto JLabel (etiqueta) que
        has debido colocar antes en el formulario y que será donde se muestre el mapa.  */
        
        //  Deja la etiqueta del formulario sin ningún texto en el diseño.
        
        javax.swing.JLabel jLabelMapa = jLabel7mapa;
        
        //  Indica aquí el tamaño que desees para el mapa
        
        int tamHorizontal = 200;
        int tamVertical = 200;
        
        /*  Puedes encontrar más información sobre el uso de mapas estáticos de Google Maps aquí:
          http://code.google.com/intl/es-ES/apis/maps/documentation/staticmaps/ */

        //A partir de aquí no hace falta cambiar nada
        
        try {
            String txtDireccionImagenMapa = "http://maps.google.com/maps/api/staticmap?path="+
                    origen+"|"+destino+"&size="+tamHorizontal+"x"+tamVertical+
                    "&language=ES&sensor=false";
            System.out.println(txtDireccionImagenMapa);
            java.awt.Toolkit toolkit = java.awt.Toolkit.getDefaultToolkit();
            java.awt.Image imagenMapa = toolkit.getImage(new java.net.URL(txtDireccionImagenMapa)); 
            jLabelMapa.setIcon(new javax.swing.ImageIcon(imagenMapa));    
        } catch(java.net.MalformedURLException e) {   
            javax.swing.JOptionPane.showMessageDialog(this, "La dirección de imagen indicada no es correcta");
        }           
        //TEXTO
        jTextArea1ticket.setText("Ticket");
        jTextArea1ticket.append("\n:::::::::");
        //TEXTO
        jTextArea1ticket.append("\nFecha:" );        
        //Mostrar fecha
        DateFormat formatoFecha = DateFormat.getDateInstance(DateFormat.MEDIUM);
        jTextArea1ticket.append(formatoFecha.format(Calendar.getInstance().getTime()));     
        //TEXTO
        jTextArea1ticket.append("\n");
        //Mostrar hora de bajada de bandera
        DateFormat formatoHorabajada = DateFormat.getTimeInstance(DateFormat.MEDIUM);       
        //TEXTO
        jTextArea1ticket.append("Hora bajada Bandera: ");
        jTextArea1ticket.append(formatoHorabajada.format(Calendar.getInstance().getTime()));
        //Contador de tiempo START
        duracion.reset();
        duracion.start();
        //Texto
        jTextArea1ticket.append("\n");
        //Longitud
        longitud = Double.valueOf(jTextField1longitud.getText());
        jLabel4Longitud.setText(decimalToDMS(longitud));
        //Latitud
        latitud = Double.valueOf(jTextField1latitud1.getText());
        jLabel3Latitud.setText(decimalToDMS(latitud));
        
        
        
        
       
    }//GEN-LAST:event_jButton1banderaVerdeActionPerformed
       
        //Variable contador
        int contador = 0;
        
        long tiempoMLS;
        
    private void jButton1cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1cancelarActionPerformed
       
        //Variable  
        
        String contadorDato;
        double tarifaMinuto = 0.50;
        
        
        
        //Sumar contador
        contador++;       
        //Dar formato al número del contador
        DecimalFormat formatoNumero = new DecimalFormat("0000");
        contadorDato = formatoNumero.format(contador);      
        //TEXTO
        jTextArea1ticket.append("\nNº Ticket: " + contadorDato);
        //Mostrar hora fin de trayecto
        DateFormat formatoHorafin = DateFormat.getTimeInstance(DateFormat.MEDIUM);       
        //TEXTO
        jTextArea1ticket.append("\nHora fin de trayecto: ");
        jTextArea1ticket.append(formatoHorafin.format(Calendar.getInstance().getTime()));
        //Duración de Trayecto
        jTextArea1ticket.append("\nDuración trayecto: ");
        //Contador de tiempo STOP y RESET
        duracion.stop();
        //Dar el tiempo
        tiempoMLS = duracion.getTime();
        duracionFormato = DurationFormatUtils.formatDurationHMS(tiempoMLS);
        jTextArea1ticket.append(duracionFormato);
        //TEXTO
        jTextArea1ticket.append("\nTarifa por minuto: ");
        //Tarifa por minuto
        NumberFormat formatoTarifaMinuto;
        formatoTarifaMinuto = NumberFormat.getCurrencyInstance(new Locale("es", "ES"));
        jTextArea1ticket.append(formatoTarifaMinuto.format(tarifaMinuto));
        //TEXTO
        jTextArea1ticket.append("\n");
        jTextArea1ticket.append("\n");
        //TEXTO
        NumberFormat formatoEuro = NumberFormat.getCurrencyInstance(new Locale("es","ES"));
        double importe = (tiempoMLS/60000)*tarifaMinuto;
        double iva = ((21 * importe) / 100);
        double importeTotal = iva + importe;
        jTextArea1ticket.append("Importe: " + String.valueOf(formatoEuro.format(importe)));
        jTextArea1ticket.append("\n");
        //IVA
        NumberFormat formatoIva;
        formatoIva = NumberFormat.getCurrencyInstance(new Locale("es", "ES"));
        jTextArea1ticket.append("I.V.A: " + formatoEuro.format(iva));
        jTextArea1ticket.append("\n");
        //TEXTO
        jTextArea1ticket.append("Importe total: " + formatoEuro.format(importeTotal));
        

    }//GEN-LAST:event_jButton1cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1banderaVerde;
    private javax.swing.JButton jButton1cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3Latitud;
    private javax.swing.JLabel jLabel4Longitud;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5imagenTaxi;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel7mapa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1ticket;
    private javax.swing.JTextField jTextField1destino;
    private javax.swing.JTextField jTextField1latitud1;
    private javax.swing.JTextField jTextField1longitud;
    private javax.swing.JTextField jTextField1tarjetaCredito;
    // End of variables declaration//GEN-END:variables
}
